import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nathan R | React Lab 3',
  description: 'Generated by Me B)',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-black via-gray-800 to-teal-900`}>{children}</body>
    </html>
  )
}
